#!/usr/bin/env bash
# g16-build-env.sh — source to build anything with Grok16 build-essential
# Generated by grok16-build-essential.sh install
set -euo pipefail
GROK16_ROOT="${GROK16_ROOT:-/home/default/Desktop/SG/Grok16}"
G16_PREFIX="${G16_PREFIX:-/home/default/Desktop/SG/Grok16}"
export GROK16_ROOT G16_PREFIX GROK16_BUILD_ESSENTIAL=1
export PATH="$G16_PREFIX/bin:$G16_PREFIX/libexec/grok16:$PATH"
export CC="${CC:-$G16_PREFIX/bin/g16}"
export CXX="${CXX:-$G16_PREFIX/bin/g16}"
export ASM="$G16_PREFIX/bin/g16-as"
export LD="$G16_PREFIX/bin/g16-ld"
export AR="$G16_PREFIX/bin/g16-ar"
export RANLIB="$G16_PREFIX/bin/g16-ranlib"
export STRIP="$G16_PREFIX/bin/g16-strip"
export NM="$G16_PREFIX/bin/g16-nm"
export OBJCOPY="$G16_PREFIX/bin/g16-objcopy"
export OBJDUMP="$G16_PREFIX/bin/g16-objdump"
export CFLAGS="${CFLAGS:-} -I/home/default/Desktop/SG/Grok16/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.2.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.2.0/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.0/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.0.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.0.0/include-fixed -I/usr/include"
export CXXFLAGS="${CXXFLAGS:-} -I/home/default/Desktop/SG/Grok16/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.2.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.2.0/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.0/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.0.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.0.0/include-fixed -I/usr/include"
export CPPFLAGS="${CPPFLAGS:-} -I/home/default/Desktop/SG/Grok16/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.2.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.2.0/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.1.0/include-fixed -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.0.0/include -I/home/default/Desktop/SG/Grok16/lib/gcc/x86_64-pc-linux-gnu/16.0.0/include-fixed -I/usr/include"
export LDFLAGS="${LDFLAGS:-} -L/home/default/Desktop/SG/Grok16/lib -L/home/default/Desktop/SG/Grok16/lib64 -Wl,-rpath,$G16_PREFIX/lib"
export LIBRARY_PATH="${LIBRARY_PATH:-}:$G16_PREFIX/lib:$G16_PREFIX/lib64"
export CMAKE_TOOLCHAIN_FILE="$GROK16_ROOT/cmake/grok16-toolchain.cmake"
export CMAKE_PROJECT_INCLUDE="$GROK16_ROOT/cmake/grok16-field.cmake"
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH:-}:$G16_PREFIX/lib/pkgconfig:$G16_PREFIX/share/pkgconfig"
export GROK16_FIELD_BUILD=1
# always-optimal — compiler symlink best settings
export G16_BELT_PROFILE="belt_2_0"
export G16_BENCH_PROFILE="belt_2_0"
export G16_ALWAYS_OPTIMAL="1"
export G16_FIELD_SPEED="1"
export G16_OPTIMAL_RUNNER="python"
export G16_OPTIMAL_PATTERN="dev_organized_python"
export G16_COMPILER_SYMLINKS="1"
export G16_OPTIMAL_COMBINATRONICS_AT_COMPILE="1"
# Eval: eval "$(./scripts/g16-build-env.sh)"
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  printf 'export GROK16_ROOT=%q G16_PREFIX=%q GROK16_BUILD_ESSENTIAL=1\n' "$GROK16_ROOT" "$G16_PREFIX"
  printf 'export PATH=%q\n' "$PATH"
  printf 'export CC=%q CXX=%q LD=%q AR=%q\n' "$CC" "$CXX" "$LD" "$AR"
  printf 'export CFLAGS=%q CXXFLAGS=%q LDFLAGS=%q\n' "$CFLAGS" "$CXXFLAGS" "$LDFLAGS"
fi
