# Grok16 thermal guard — AMOURANTHRTX dispatch mirrors NewLatest field-thermal-guard doctrine.
# Include from field-cmake / queen-rtx profiles after grok16-profile-field-opt.cmake.

if(NOT DEFINED NEXUS_FIELD_MAX_JOULES_PER_SEC)
  set(NEXUS_FIELD_MAX_JOULES_PER_SEC "45")
endif()
if(NOT DEFINED NEXUS_FIELD_REDATA_CHUNK)
  set(NEXUS_FIELD_REDATA_CHUNK "8192")
endif()
if(NOT DEFINED NEXUS_FIELD_HOTSPOT_DELTA_C)
  set(NEXUS_FIELD_HOTSPOT_DELTA_C "4")
endif()

add_compile_definitions(
  G16_FIELD_THERMAL_GUARD=1
  G16_FIELD_HOTSPOT_DELTA_C=${NEXUS_FIELD_HOTSPOT_DELTA_C}
  G16_FIELD_MAX_JOULES_PER_SEC=${NEXUS_FIELD_MAX_JOULES_PER_SEC}
  G16_FIELD_REDATA_CHUNK=${NEXUS_FIELD_REDATA_CHUNK}
  FIELD_THERMAL_INCREMENTAL_REDATA=1
  FIELD_HOTSPOT_ADVISORY=1
)