# RTX/NVIDIA foreign path CLOSED by default on Field Grok16
set(G16_RTX_PERMIT OFF)
if(DEFINED ENV{NEXUS_RTX_PERMIT})
  if("$ENV{NEXUS_RTX_PERMIT}" STREQUAL "1")
    set(G16_RTX_PERMIT ON)
  endif()
endif()
if(NOT G16_RTX_PERMIT)
  message(STATUS "Grok16 RTX gate CLOSED — foreign GPU exploit surface dispermitted")
  add_compile_definitions(G16_RTX_CLOSED=1 G16_NO_NVIDIA=1)
endif()
